알림 화면 UI 초안
YAPP-Github/20th-ALL-Rounder-Team-2-iOS pull request #111
Opened 2022-05-29 11:49 UTC by yjyoon-dev

- resolved: #96

<img width="50%" src="https://user-images.githubusercontent.com/72238126/170866444-4ef23354-36b8-4204-85fc-1f46b3b856a4.png" />

2022-05-30 01:48 UTC, laco-dev requested changes

2022-05-30 01:48 UTC, laco-dev commented on modules/domain/src/main/java/kr/co/knowledgerally/domain/model/Notification.kt
> +)
피그마에 있는 기획 내용입니다.
```
1. 수강 클래스는 플레이어 입장에서 취한 액션에 대한 알림 전체가 전송된다. 
2. 플레이어 전용 알림 아이콘과 헤딩을 통해서 유저가 구분할 수 있다.  
3. 알림 내용은 다음과 같다.  
   a. 알림 내용 텍스트 
    b. 클래스 제목  
   c. 상대 유저 이름 (플레이어 입장이라면 코치 이름, 코치 입장이라면 플레이어 이름) 
   d. 상단 알림 수신 날짜
```

2022-05-30 01:48 UTC, laco-dev commented on modules/domain/src/main/java/kr/co/knowledgerally/domain/model/Notification.kt
> +    val type: String // "Coach" or "Player"
이 타입도 enum 클래스로 만들어 주세요.
String -> 변환 하는것은 가장 좋지 않은 방법입니다.

2022-05-30 01:48 UTC, laco-dev commented on modules/domain/src/main/java/kr/co/knowledgerally/domain/model/Notification.kt
> +    val date: String,
도메인 모델에서는 String으로 가지는 대신 명확한 날짜 타입을 사용합니다.
LocalDate 타입으로 만들어 주세요

2022-05-30 01:48 UTC, laco-dev commented on modules/domain/src/main/java/kr/co/knowledgerally/domain/usecase/GetNotificationUseCase.kt
> +class GetNotificationUseCase @Inject constructor() {
리스트 형태를 반환할 때에는 뒤에 List를 붙여주세요.
`GetNotificationListUseCase`

2022-05-30 01:48 UTC, laco-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/model/NotificationModel.kt
> +    }
String resource로 만들어 주세요

2022-05-30 01:48 UTC, laco-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/model/NotificationModel.kt
> +    enum class Type { Coach, Player, /* ... */ }
뒤에 확장될 가능성이 전혀 없어 보입니다.
주석 제거 해주세요

2022-05-30 01:48 UTC, laco-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/notification/NotificationScreen.kt
> +    onClickItem: () -> Unit
이벤트에 대한 이름을 작성할 때에는 `on + Target + Behavior` 형태로 합니다.
아래 형태로 만들어주세요
```
onNotifiactionClick: (NotificationModel) -> Unit
```

2022-05-30 01:48 UTC, laco-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/notification/NotificationScreen.kt
> +    Scaffold(
Scaffold를 사용한 장점이 무엇인가요?

2022-05-30 01:48 UTC, laco-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/notification/NotificationScreen.kt
> +            VerticalSpacer(24.dp)
LazyColumn의 padding을 같이 활용 해주세요.
상단, 하단만 제외하고 여백을 먹이는 방법이 있습니다

2022-05-30 01:48 UTC, laco-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/notification/NotificationScreen.kt
> +                    .size(48.dp, 48.dp)
`size(size: Dp)`

2022-05-30 01:48 UTC, laco-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/notification/NotificationScreen.kt
> +                "${notification.lessonName} | ${notification.opponentName}",
파라미터 이름을 붙여 주세요 text = ...

2022-05-30 01:48 UTC, laco-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/notification/NotificationScreen.kt
> +            lessonName = "윤영직의 안드로이드 교실",
😅

2022-05-30 01:48 UTC, laco-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/notification/NotificationScreen.kt
> +        }
NotificationContent(...) 컴포저블로 분리 해주세요

2022-05-30 01:48 UTC, laco-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/notification/NotificationViewModel.kt
> +        viewModelScope.launch {
BaseViewModel의 launch 사용 해주세요

2022-05-30 01:48 UTC, laco-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/notification/NotificationViewModel.kt
> +                        else NotificationUiState.Empty
코틀린 컨벤션으로 한 줄로 간단힌 표현할 수 없는 if, else 구문은 반드시 괄호를 열어 여러줄로 표현합니다.
https://kotlinlang.org/docs/control-flow.html#if-expression

2022-05-30 03:13 UTC, yjyoon-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/model/NotificationModel.kt
> +    enum class Type { Coach, Player, /* ... */ }
피그마에서 `title`이 **운영 클래스**와 **수강 클래스** 외에도 **취소된 클래스**가 있더라구요.
또 후기 작성 관련 알림도 있던데 얘도 따로 타입을 만들어야 하지 않을까 생각했습니다.
그리고 추후에 세부적인 알림 허용 여부를 설정할 때를 고려해서 매칭 성공, 매칭 실패 등 
알림 유형을 굉장히 세부적으로 나눠야하지 않을까 생각했습니다.

2022-05-30 03:27 UTC, yjyoon-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/notification/NotificationScreen.kt
> +    Scaffold(
음.. 저는 `TopAppBar`를 쉽게 배치하려고 사용했습니다

2022-05-30 03:27 UTC, laco-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/model/NotificationModel.kt
> +    enum class Type { Coach, Player, /* ... */ }
취소된 클래스와 "운영 클래스" "수강 클래스"가 같은 레벨의 개념일까요?

운영 클래스도 취소될 수 있고
수강 클래스도 취소될 수 있지 않나요?

2022-05-30 03:32 UTC, yjyoon-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/model/NotificationModel.kt
> +    enum class Type { Coach, Player, /* ... */ }
운영 클래스와 수강 클래스가 상위 개념이군요.
취소, 후기 등등은 별도로 관리하도록 하겠습니다.

2022-05-30 12:26 UTC, laco-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/notification/NotificationScreen.kt
> +    Scaffold(
그냥 Row로 해서 만든것과 비교해서 어떤 장점이 있나요?

2022-05-30 13:25 UTC, yjyoon-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/notification/NotificationScreen.kt
> +    Scaffold(
`TopAppBar`도 결국 `Row`로 구현되어 있을거라 딱히 장점은 없을 것 같습니다.
다만 `TopAppBar`를 고려한 `innerPadding` 값을 쉽게 받을 수 있다 정도인 것 같습니다.

2022-05-30 13:26 UTC, laco-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/notification/NotificationScreen.kt
> +    Scaffold(
`innerPadding`이 어떤 역할을 하는지 알려주실 수 있나요!?

2022-05-30 13:48 UTC, yjyoon-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/notification/NotificationScreen.kt
> +    Scaffold(
음 `TopBar`와 `BottomBar`의 오프셋을 고려한 내부 컨텐츠 패딩 값을 주는거로 알고있습니다

2022-05-30 13:57 UTC, laco-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/notification/NotificationScreen.kt
> +    Scaffold(
굳이 Row를 써도 되는 내용에 불필요한 기능 같습니다.

2022-05-30 14:15 UTC, yjyoon-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/notification/NotificationScreen.kt
> +    Scaffold(
`NavigationBar`도 없는 화면이라 확실히 불필요한 것 같네요. 수정하겠습니다!

2022-05-30 17:18 UTC, yjyoon-dev commented on modules/domain/src/main/java/kr/co/knowledgerally/domain/model/Notification.kt
> +    val type: String // "Coach" or "Player"
Notification 모델 수정 했습니다.

[1dfaca8](https://github.com/YAPP-Github/20th-ALL-Rounder-Team-2-Android/pull/111/commits/1dfaca86d36f6102223babefd0dc5d0cac1cc331)

2022-05-30 17:18 UTC, yjyoon-dev commented on modules/domain/src/main/java/kr/co/knowledgerally/domain/model/Notification.kt
> +)
Notification 모델 수정 했습니다.

[1dfaca8](https://github.com/YAPP-Github/20th-ALL-Rounder-Team-2-Android/pull/111/commits/1dfaca86d36f6102223babefd0dc5d0cac1cc331)

2022-05-30 17:18 UTC, yjyoon-dev commented on modules/domain/src/main/java/kr/co/knowledgerally/domain/model/Notification.kt
> +    val date: String,
Notification 모델 수정 했습니다.

[1dfaca8](https://github.com/YAPP-Github/20th-ALL-Rounder-Team-2-Android/pull/111/commits/1dfaca86d36f6102223babefd0dc5d0cac1cc331)

2022-05-30 17:18 UTC, yjyoon-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/model/NotificationModel.kt
> +    }
Notification 모델 수정 했습니다.

[1dfaca8](https://github.com/YAPP-Github/20th-ALL-Rounder-Team-2-Android/pull/111/commits/1dfaca86d36f6102223babefd0dc5d0cac1cc331)

2022-05-30 17:19 UTC, yjyoon-dev commented on modules/domain/src/main/java/kr/co/knowledgerally/domain/usecase/GetNotificationUseCase.kt
> +class GetNotificationUseCase @Inject constructor() {
이름 수정했습니다.

[cfc5f63](https://github.com/YAPP-Github/20th-ALL-Rounder-Team-2-Android/pull/111/commits/cfc5f637c008569711401f6373e6e064c4bba4a5)

2022-05-30 17:19 UTC, yjyoon-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/notification/NotificationScreen.kt
> +                "${notification.lessonName} | ${notification.opponentName}",
리팩토링했습니다.

[8a819a7](https://github.com/YAPP-Github/20th-ALL-Rounder-Team-2-Android/pull/111/commits/8a819a70bef4c021b8e35a6bb929e1502514f42d)

2022-05-30 17:19 UTC, yjyoon-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/notification/NotificationScreen.kt
> +        }
리팩토링했습니다.

[8a819a7](https://github.com/YAPP-Github/20th-ALL-Rounder-Team-2-Android/pull/111/commits/8a819a70bef4c021b8e35a6bb929e1502514f42d)

2022-05-30 17:19 UTC, yjyoon-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/notification/NotificationViewModel.kt
> +        viewModelScope.launch {
사용하도록 변경했습니다.

[874ec3d](https://github.com/YAPP-Github/20th-ALL-Rounder-Team-2-Android/pull/111/commits/874ec3d22e80d32bd6554a0e0b6c33732ab30839)

2022-05-30 17:20 UTC, yjyoon-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/notification/NotificationViewModel.kt
> +                        else NotificationUiState.Empty
전에도 지적해주신 것 같은데 죄송합니다 ㅠㅠ 수정했습니다.

[874ec3d](https://github.com/YAPP-Github/20th-ALL-Rounder-Team-2-Android/pull/111/commits/874ec3d22e80d32bd6554a0e0b6c33732ab30839)

2022-05-30 17:20 UTC, yjyoon-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/notification/NotificationScreen.kt
> +    onClickItem: () -> Unit
수정했습니다.

[5297404](https://github.com/YAPP-Github/20th-ALL-Rounder-Team-2-Android/pull/111/commits/52974048431371f04b922ffce035bc5f98f7e413)

2022-05-30 17:20 UTC, yjyoon-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/notification/NotificationScreen.kt
> +                    .size(48.dp, 48.dp)
리팩토링했습니다.

[8a819a7](https://github.com/YAPP-Github/20th-ALL-Rounder-Team-2-Android/pull/111/commits/8a819a70bef4c021b8e35a6bb929e1502514f42d)

2022-05-30 17:21 UTC, yjyoon-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/notification/NotificationScreen.kt
> +    Scaffold(
리팩토링했습니다.

[8a819a7](https://github.com/YAPP-Github/20th-ALL-Rounder-Team-2-Android/pull/111/commits/8a819a70bef4c021b8e35a6bb929e1502514f42d)

2022-05-30 17:21 UTC, yjyoon-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/model/NotificationModel.kt
> +    enum class Type { Coach, Player, /* ... */ }
Notification 모델 수정 했습니다.

[1dfaca8](https://github.com/YAPP-Github/20th-ALL-Rounder-Team-2-Android/pull/111/commits/1dfaca86d36f6102223babefd0dc5d0cac1cc331)

2022-05-30 17:21 UTC, yjyoon-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/notification/NotificationScreen.kt
> +            VerticalSpacer(24.dp)
`Arrangement.spacedBy()` 사용했습니다.

[ebc95c6](https://github.com/YAPP-Github/20th-ALL-Rounder-Team-2-Android/pull/111/commits/ebc95c6e844abacb5a071fac7a0cd84be6d91e40)

2022-06-01 05:50 UTC, laco-dev requested changes

2022-06-01 05:50 UTC, laco-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/model/NotificationModel.kt
>      }
icon과 같이 titleRes로 만들어주세요

2022-06-01 05:50 UTC, laco-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/notification/NotificationScreen.kt
> +}
Info라는 네이밍은 가급적 지양 해주세요.
다른 좋은 이름은 없을까요?

2022-06-01 06:56 UTC, yjyoon-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/notification/NotificationScreen.kt
> +}
혹시 Info 네이밍을 지양하는 이유를 알 수 있을까요?

2022-06-01 06:58 UTC, yjyoon-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/notification/NotificationScreen.kt
> +}
다른 좋은 이름으로는 `subtitle`, `reference`, `detail` ... 정도 떠올려봤는데 딱 꽃히는게 떠오르지 않네요 ㅠㅠ

2022-06-01 17:48 UTC, merged

2022-06-02 08:57 UTC, yjyoon-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/model/NotificationModel.kt
>      }
반영했습니다.

[0ea73ab](https://github.com/YAPP-Github/20th-ALL-Rounder-Team-2-Android/pull/111/commits/0ea73abe66060a54017cc39c9a3dd5892548aa2c)

2022-06-02 08:57 UTC, yjyoon-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/notification/NotificationScreen.kt
> +}
`Subtext`로 네이밍 변경했습니다.

[0ea73ab](https://github.com/YAPP-Github/20th-ALL-Rounder-Team-2-Android/pull/111/commits/0ea73abe66060a54017cc39c9a3dd5892548aa2c)