볼 내역 UI 초안
YAPP-Github/20th-ALL-Rounder-Team-2-iOS pull request #113
Opened 2022-05-31 13:20 UTC by yjyoon-dev

- resolved: #108

<img width="50%" src="https://user-images.githubusercontent.com/72238126/171182951-79916334-b4a7-4f52-8e6e-d8ceaf56ac9c.png" />

2022-06-01 08:10 UTC, laco-dev requested changes

2022-06-01 08:10 UTC, laco-dev commented on modules/domain/src/main/java/kr/co/knowledgerally/domain/model/Ball.kt
> +value class Ball(val value: Int)
Ball이 무슨 값을 가지는가? 라는 의문이 듭니다.
BallCount가 맞지 않을까요?

2022-06-01 08:10 UTC, laco-dev commented on modules/domain/src/main/java/kr/co/knowledgerally/domain/repo/BallRepository.kt
> +    suspend fun getBallHistoryList(): Result<List<BallHistory>>
함수 이름은 List 대신 복수형으로 만들어주세요.

2022-06-01 08:10 UTC, laco-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/ball/BallUiState.kt
> +}
BallUiState가 Ball을 가지고 있는 개념이 아닌가요?

2022-06-01 08:10 UTC, laco-dev commented on modules/domain/src/main/java/kr/co/knowledgerally/domain/model/BallHistory.kt
> +) {
BallHistory가 Ball을 가지고 있을거라 생각되는데 Ball과 BallHistory는 무슨 차이인가요?

2022-06-01 08:10 UTC, laco-dev commented on modules/domain/src/main/java/kr/co/knowledgerally/domain/model/BallHistory.kt
> +    }
Plus, Minus 타입이 어떤 의미를 가지나요?
볼의 갯수 변화로 봐야 하지 않나요?

2022-06-01 08:10 UTC, laco-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/ball/BallScreen.kt
> +        }
BallTopAppBar()

2022-06-01 08:10 UTC, laco-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/ball/BallScreen.kt
> +            modifier = Modifier.padding(start = 24.dp, top = 24.dp, end = 24.dp, bottom = 0.dp)
👍

2022-06-01 08:10 UTC, laco-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/ball/BallScreen.kt
> +            Text(text = "${ball.value}개", style = KnowllyTheme.typography.headline4)
stringResource로 format 작성 해주세요

2022-06-01 08:10 UTC, laco-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/ball/BallScreen.kt
> +fun BallHelp() {
Banner라는 이름으로 추천드립니다

2022-06-01 08:16 UTC, yjyoon-dev commented on modules/domain/src/main/java/kr/co/knowledgerally/domain/model/BallHistory.kt
> +) {
볼 갯수 같은 경우에는 볼 내역 화면 뿐만 아니라 다른 화면에서 상단바에 표시되는 경우가 있더라구요.
그래서 볼 갯수만을 나타내는 `Ball` 모델과 볼 내역을 나타내는 `BallHistory` 모델을 따로 만들어야 한다고 생각했습니다.

2022-06-01 08:22 UTC, yjyoon-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/ball/BallUiState.kt
> +}
네이밍을 좀 애매하게 한 것 같습니다.
`Ball`과는 상관없이 오로지 `BallHistory`에 대한 UiState 로 생각했습니다.

2022-06-01 08:25 UTC, yjyoon-dev commented on modules/domain/src/main/java/kr/co/knowledgerally/domain/model/BallHistory.kt
> +    }
`type`은 차감인지 획득인지에 대한 구분으로 생각했고,
`count`는 차감 또는 획득한 볼의 갯수(절댓값)으로 생각했습니다.
네이밍이 애매했던 것 같습니다..

2022-06-01 08:28 UTC, yjyoon-dev commented on modules/domain/src/main/java/kr/co/knowledgerally/domain/model/Ball.kt
> +value class Ball(val value: Int)
고민을 조금 했었는데,
그러면 `Ball`이라는 이름을 갖는 모델이 없게 돼버려서 조금 어색하지 않을까해서 이렇게 했었습니다.
모델이 의미하는 바는 `BallCount`가 맞습니다.

2022-06-01 08:29 UTC, laco-dev commented on modules/domain/src/main/java/kr/co/knowledgerally/domain/model/Ball.kt
> +value class Ball(val value: Int)
내 볼 갯수를 유저에 묶을건지 별도로 가져올건지는 물어봐야 할 것 같습니다.
볼만 따로 가져올 일이 없을 것 같습니다.

2022-06-01 08:29 UTC, yjyoon-dev commented on modules/domain/src/main/java/kr/co/knowledgerally/domain/repo/BallRepository.kt
> +    suspend fun getBallHistoryList(): Result<List<BallHistory>>
혹시 네이밍에서 List 또는 복수형을 사용하는 곳의 구분법을 알 수 있을까요?

2022-06-01 08:30 UTC, laco-dev commented on modules/domain/src/main/java/kr/co/knowledgerally/domain/repo/BallRepository.kt
> +    suspend fun getBallHistoryList(): Result<List<BallHistory>>
클래스 이름으로는 List형태를 붙이고 함수에서는 복수형태로 사용합니다

2022-06-02 08:44 UTC, yjyoon-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/ball/BallScreen.kt
> +            Text(text = "${ball.value}개", style = KnowllyTheme.typography.headline4)
반영하였습니다.

[2f22627](https://github.com/YAPP-Github/20th-ALL-Rounder-Team-2-Android/pull/113/commits/2f22627b1b0b74f2c3d2fc1e3dbe44e845506d0a)

2022-06-02 08:44 UTC, yjyoon-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/ball/BallScreen.kt
> +        }
반영하였습니다.

[2f22627](https://github.com/YAPP-Github/20th-ALL-Rounder-Team-2-Android/pull/113/commits/2f22627b1b0b74f2c3d2fc1e3dbe44e845506d0a)

2022-06-02 08:45 UTC, yjyoon-dev commented on modules/domain/src/main/java/kr/co/knowledgerally/domain/model/BallHistory.kt
> +    }
모델 수정하였습니다. 
백엔드와 얘기해보았는데, 아직 볼 엔티티에 대해 확정된 것이 없어 우선 임시로 생각해야할 것 같습니다.

[312b71b](https://github.com/YAPP-Github/20th-ALL-Rounder-Team-2-Android/pull/113/commits/312b71b6d52a71c988c9e516f0870bf870f39ae5)

2022-06-02 08:46 UTC, yjyoon-dev commented on modules/domain/src/main/java/kr/co/knowledgerally/domain/model/Ball.kt
> +value class Ball(val value: Int)
백엔드와 상의해본 결과, 확정 사항은 아니지만 유저에 완전히 묶일 것 같습니다.

2022-06-02 08:46 UTC, yjyoon-dev commented on modules/domain/src/main/java/kr/co/knowledgerally/domain/repo/BallRepository.kt
> +    suspend fun getBallHistoryList(): Result<List<BallHistory>>
네이밍 수정하였습니다.

[6e512be](https://github.com/YAPP-Github/20th-ALL-Rounder-Team-2-Android/pull/113/commits/6e512be4ba0d68c9bf932d52b10527d171f0c861)

2022-06-02 09:02 UTC, yjyoon-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/ball/BallScreen.kt
> +fun BallHelp() {
네이밍 수정하였습니다.

[6e512be](https://github.com/YAPP-Github/20th-ALL-Rounder-Team-2-Android/pull/113/commits/6e512be4ba0d68c9bf932d52b10527d171f0c861)

2022-06-04 07:31 UTC, laco-dev approved these changes

2022-06-04 07:31 UTC, laco-dev commented on modules/domain/src/main/java/kr/co/knowledgerally/domain/model/BallHistory.kt
> +    val delta: Int
`changedBallCount: Int`

2022-06-04 07:59 UTC, yjyoon-dev commented on modules/domain/src/main/java/kr/co/knowledgerally/domain/model/BallHistory.kt
> +    val delta: Int
네이밍 수정했습니다.

[f6b6523](https://github.com/YAPP-Github/20th-ALL-Rounder-Team-2-Android/pull/113/commits/f6b6523bbed6e76588ffe35a144fcb4ffba01533)

2022-06-04 08:04 UTC, merged