로그인 및 회원가입 UI
YAPP-Github/20th-ALL-Rounder-Team-2-iOS pull request #129
Opened 2022-06-11 11:53 UTC by yjyoon-dev

- resolved: #114

![image](https://user-images.githubusercontent.com/72238126/173186751-5928af97-9de2-4e21-9610-06582c7f3620.png)

2022-06-11 14:42 UTC, laco-dev requested changes
StateHolder랑 상태 로직을 좀 구조화 해야할 것 같아서, 
가입쪽 로직은 제가 리팩토링 따로 진행 해보겠습니다.

남겨드린 피드백 위주로 확인 해주세요

2022-06-11 14:42 UTC, laco-dev commented on modules/app/src/main/AndroidManifest.xml
> +
불필요한 코드체인지가 많아져서 두개는 나눠서 작업 했으면 좋았을 것 같네요.

2022-06-11 14:42 UTC, laco-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/login/LoginScreen.kt
> +                painter = painterResource(id = R.drawable.img_login_illustration),
이미지 `drawable-xxxhdpi`로 옮겨주세요

2022-06-11 14:42 UTC, laco-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/component/KnowllyCheckBox.kt
> +@OptIn(ExperimentalMaterial3Api::class)
이거 제거해도 됩니다

2022-06-11 14:42 UTC, laco-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/component/KnowllyCheckBox.kt
> +import androidx.compose.material.Text
`material3.Text` 로 바꿔주세요~
다른곳도 모두 변경 해주세요

2022-06-11 14:42 UTC, laco-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/component/KnowllyCheckBox.kt
> +fun KnowllyCheckBoxTile(
`Tile`은 무슨 의미인가요?

2022-06-11 14:42 UTC, laco-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/component/KnowllyCheckBox.kt
> +    }
```kotlin
CompositionLocalProvider(LocalMinimumTouchTargetEnforcement provides false) { ... }
```
`LocalMinimumTouchTargetEnforcement` 속성은 기본 크기를 48로 강제로 조정합니다.
시안과 여백이 달라지기 때문에 위 속성을 끄고 직접 처리 해주세요.

단순하게 끄면 아래처럼 그려집니다.

<img src="https://user-images.githubusercontent.com/28249981/173191835-8b9377d2-eb23-49d9-a698-f5761054bced.png" width=360/>

2022-06-11 14:42 UTC, laco-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/login/LoginActivity.kt
> +                onShowPolicy = { startPolicyActivity() }
`onShow`라는 이름은 무언가 보여졌다. 라는 콜백으로 느껴집니다.
`navigateToXXX`로 맞춰주세요

2022-06-11 14:42 UTC, laco-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/login/LoginScreen.kt
> +                modifier = Modifier.padding(vertical = 36.dp)
아이템 여백 대신 verticalArrangment에 
```kotlin
verticalArrangement = Arrangement.spacedBy(36.dp, Alignment.CenterVertically)
```
속성으로 대체해도 됩니다.

2022-06-11 14:42 UTC, laco-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/login/LoginScreen.kt
> +    ) {
Button을 사용할 필요가 없어 보여요, `Surface`로 만들어보면 어떨까요?

2022-06-11 14:42 UTC, laco-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/login/LoginScreen.kt
> +            )
아이콘 크기만큼 오른쪽으로 밀려서 텍스트가 가운데에서 오른쪽으로 밀려나 있는데요.
텍스트가 가운데에 위치하도록 개선해보면 좋겠습니다.

2022-06-11 14:42 UTC, laco-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/login/LoginScreen.kt
> +    val acceptionString = stringResource(id = R.string.login_acception)
https://search.naver.com/search.naver?where=nexearch&sm=top_hty&fbm=0&ie=utf8&query=acception
명사 표현이 다른 것 같네요?

2022-06-11 14:42 UTC, laco-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/login/LoginScreen.kt
> +        acceptionString.indexOf(policyString) + policyString.length
indexOf()가 불필요하게 두번 호출되서 계산되고 있습니다.
한 번만 호출하도록 만들어주세요.

2022-06-11 14:42 UTC, laco-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/login/LoginScreen.kt
> +        text = buildAnnotatedString {
Span쪽은 아직 저도 잘 몰라서, 천천히 살펴보겠습니다

2022-06-11 14:42 UTC, laco-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/login/LoginViewModel.kt
> +    fun login(token: KakaoAccessToken) {
일부로 KakaoAccessToken과 의존성을 없앴는데 다시 추가한 이유가 있나요.

2022-06-11 14:43 UTC, laco-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/login/LoginScreen.kt
> +            )
![image](https://user-images.githubusercontent.com/28249981/173192559-d253749b-3837-42e2-99e4-529a8027b4f2.png)

2022-06-11 15:05 UTC, yjyoon-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/login/LoginScreen.kt
> +            )
![image](https://user-images.githubusercontent.com/72238126/173193302-978b2c12-9079-41ad-a998-4007fce65efc.png)

카카오 로그인 디자인 가이드를 참고해서 의도한 구현이긴 합니다.
디자이너와 의논해볼까요..?

2022-06-11 16:48 UTC, yjyoon-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/login/LoginScreen.kt
> +                painter = painterResource(id = R.drawable.img_login_illustration),
[f0b886a](https://github.com/YAPP-Github/20th-ALL-Rounder-Team-2-Android/pull/129/commits/f0b886a65665405b410e8a8b9c1dbce930f48f19)

이미지 파일 이동하였습니다.

2022-06-11 16:48 UTC, yjyoon-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/component/KnowllyCheckBox.kt
> +@OptIn(ExperimentalMaterial3Api::class)
[f786502](https://github.com/YAPP-Github/20th-ALL-Rounder-Team-2-Android/pull/129/commits/f7865022d3a053384ce991d852822095e7439360)

제거했습니다.

2022-06-11 16:49 UTC, yjyoon-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/component/KnowllyCheckBox.kt
> +import androidx.compose.material.Text
[0b1e7a0](https://github.com/YAPP-Github/20th-ALL-Rounder-Team-2-Android/pull/129/commits/0b1e7a085440a88c5c5104f752ecdf082a9f0963)

`material` 사용했던 곳 `material3`로 일괄 수정 했습니다.

2022-06-11 16:49 UTC, yjyoon-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/component/KnowllyCheckBox.kt
> +fun KnowllyCheckBoxTile(
[4ecff4f](https://github.com/YAPP-Github/20th-ALL-Rounder-Team-2-Android/pull/129/commits/4ecff4fecbce06c43010d77ece735921197bdb26)

조언주신대로 `KnowllyCheckBoxText`로 컴포저블명 변경하였습니다.

2022-06-11 16:50 UTC, yjyoon-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/component/KnowllyCheckBox.kt
> +    }
[4ecff4f](https://github.com/YAPP-Github/20th-ALL-Rounder-Team-2-Android/pull/129/commits/4ecff4fecbce06c43010d77ece735921197bdb26)

해당 코드 참고하여 `CheckBox` 강제 여백 제거하고 리팩토링 했습니다.

2022-06-11 16:50 UTC, yjyoon-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/login/LoginActivity.kt
> +                onShowPolicy = { startPolicyActivity() }
[31cebaa](https://github.com/YAPP-Github/20th-ALL-Rounder-Team-2-Android/pull/129/commits/31cebaab6fbb9b83b6d79be835dfed83a7c2b7f2)

네미밍 수정하였습니다.

2022-06-11 16:51 UTC, yjyoon-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/login/LoginScreen.kt
> +                modifier = Modifier.padding(vertical = 36.dp)
[89a198e](https://github.com/YAPP-Github/20th-ALL-Rounder-Team-2-Android/pull/129/commits/89a198e997a233c64a8fb38d72f6defc7786dd66)

해당 함수 사용하여 리팩토링했습니다.

2022-06-11 16:51 UTC, yjyoon-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/login/LoginScreen.kt
> +    ) {
[cd031bf](https://github.com/YAPP-Github/20th-ALL-Rounder-Team-2-Android/pull/129/commits/cd031bff73bea6762fd6cc933d46c2892e7c220a)

`Button`을 사용하지 않고 `Surface`만으로 구현했습니다.

2022-06-11 16:51 UTC, yjyoon-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/login/LoginScreen.kt
> +    val acceptionString = stringResource(id = R.string.login_acception)
[d809829](https://github.com/YAPP-Github/20th-ALL-Rounder-Team-2-Android/pull/129/commits/d80982963f3aee60cc65f88375939845e9d7c64f)

acception -> acceptation 으로 수정하였습니다.😅

2022-06-11 16:52 UTC, yjyoon-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/login/LoginScreen.kt
> +        acceptionString.indexOf(policyString) + policyString.length
[1ed5b2f](https://github.com/YAPP-Github/20th-ALL-Rounder-Team-2-Android/pull/129/commits/1ed5b2fbf3283a3adb26e42cc41413e2a7202688)

`IntRange`를 한 번만 계산하도록 성능 개선하였습니다.

2022-06-11 16:54 UTC, yjyoon-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/login/LoginViewModel.kt
> +    fun login(token: KakaoAccessToken) {
[98516e5](https://github.com/YAPP-Github/20th-ALL-Rounder-Team-2-Android/pull/129/commits/98516e5e68bc331df80625cbd3e274d218c85229)

같은 `presentation` 모듈 안에 구현되어 있어서 그랬던건데,
ui와 feature 패키지 간의 의존성은 고려하지 못했습니다. 다시 수정했습니다.

2022-06-12 01:29 UTC, laco-dev approved these changes

2022-06-12 01:29 UTC, merged