KnowllyTopAppBar MainScreen 적용
YAPP-Github/20th-ALL-Rounder-Team-2-iOS pull request #146
Opened 2022-06-13 10:16 UTC by yjyoon-dev

- resolved: #139

2022-06-13 10:18 UTC, yjyoon-dev commented
단계 별로 리뷰 받고자 MyPageScreen 경우만 작업해두었습니다.

2022-06-13 14:42 UTC, laco-dev requested changes

2022-06-13 14:42 UTC, laco-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/main/MainScreen.kt
> +                }
화면마다 AppBar를 추가할 이유가 없습니다.
하나만 추가 해주세요

2022-06-13 14:42 UTC, laco-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/mypage/MyPageScreen.kt
> +        // )
관련된 코드 모두 지워주세요

2022-06-15 09:58 UTC, yjyoon-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/mypage/MyPageScreen.kt
> +        // )
[a3d7fe3](https://github.com/YAPP-Github/20th-ALL-Rounder-Team-2-Android/pull/146/commits/a3d7fe3590cd9f67dd2cc9f9bf05668da06c3d39)}

제거했습니다

2022-06-15 09:58 UTC, yjyoon-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/main/MainScreen.kt
> +                }
[40bcc7b](https://github.com/YAPP-Github/20th-ALL-Rounder-Team-2-Android/pull/146/commits/40bcc7b1db4a4d36f6bf00ca01601bbb02496e4c)

하나만 등록하였고, Home 화면 경우에만 분기 처리 했습니다.

2022-06-15 14:41 UTC, laco-dev approved these changes

2022-06-16 00:21 UTC, merged