알림 - UI 수정사항 반영
YAPP-Github/20th-ALL-Rounder-Team-2-iOS pull request #150
Opened 2022-06-16 16:58 UTC by yjyoon-dev

## 이슈
- resolved: #147 

![image](https://user-images.githubusercontent.com/72238126/174125688-b25a93e2-9cec-4bfd-8270-1e1df73d04aa.png)

2022-06-16 17:00 UTC, yjyoon-dev commented
알림 유형이 9개 정도로 나뉘고 이에 따른 텍스트 내용이나 터치 시 이동 화면이 모두 달라서
이는 따로 이슈 파서 작업하도록 하겠습니다.

2022-06-17 13:10 UTC, laco-dev commented
> 알림 유형이 9개 정도로 나뉘고 이에 따른 텍스트 내용이나 터치 시 이동 화면이 모두 달라서
이는 따로 이슈 파서 작업하도록 하겠습니다.

모든 타입을 앱에서 가질 필요가 없습니다.
서버에서 타입에 따른 이미지도 같이 내려주게 하면 됩니다.
이동은 딥링크 사용하고요

2022-06-17 13:13 UTC, laco-dev requested changes

2022-06-17 13:13 UTC, laco-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/model/NotificationModel.kt
> +    date = date.format(DateTimeFormatter.ofPattern("M월 d일")),
UI에서 만들도록 해주세요

2022-06-17 13:13 UTC, laco-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/notification/NotificationScreen.kt
> +            .height(124.dp)
높이를 하드코딩 하지 말고, 패딩으로 계산되도록 해주세요

2022-06-17 17:10 UTC, yjyoon-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/model/NotificationModel.kt
> +    date = date.format(DateTimeFormatter.ofPattern("M월 d일")),
[80434d3](https://github.com/YAPP-Github/20th-ALL-Rounder-Team-2-Android/pull/150/commits/80434d318ea73f932addf80380ad5cfb9fe6493c)

수정하였습니다.

2022-06-17 17:11 UTC, yjyoon-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/notification/NotificationScreen.kt
> +            .height(124.dp)
[80434d3](https://github.com/YAPP-Github/20th-ALL-Rounder-Team-2-Android/pull/150/commits/80434d318ea73f932addf80380ad5cfb9fe6493c)

이미 패딩 계산이 되어있었어서 높이 관련 코드만 제거했습니다.

2022-06-18 02:36 UTC, laco-dev approved these changes

2022-06-18 03:02 UTC, merged