수강 클래스 - UI
YAPP-Github/20th-ALL-Rounder-Team-2-iOS pull request #160
Opened 2022-06-18 14:14 UTC by yjyoon-dev

## 이슈
- resolved: #153 

![image](https://user-images.githubusercontent.com/72238126/174442371-3ed8f15f-04d0-41a4-9c74-390bce0fbe37.png)

2022-06-18 14:16 UTC, yjyoon-dev commented
후기 작성 화면 이동을 제외하고 구현하였습니다.

2022-06-19 03:16 UTC, laco-dev requested changes

2022-06-19 03:16 UTC, laco-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/player/CopyButton.kt
> +    kakaoId: String,
이름은 CopyButton인데 카카오에 의존성이 강하게 걸린 것 같습니다.
전용적으로 만들거나 범용적으로 만들거나 둘 중 하나만 해주세요

2022-06-19 03:16 UTC, laco-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/player/PlayerContent.kt
> +        item { KnowllyDivider() }
Divider가 item으로 판단할 필요가 있을까요

2022-06-19 03:16 UTC, laco-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/player/PlayerUiState.kt
> +    object Empty : PlayerUiState()
수강 클래스는 Empty 상태가 없습니다.

2022-06-19 03:16 UTC, laco-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/player/ReviewOutlinedBadge.kt
> +                    modifier = Modifier.padding(start = 2.dp),
아이콘 크기 다시 봐주세요
ic_check 임시로 넣은건데 리소스 에셋에서 다시 넣어주세요.

2022-06-19 04:20 UTC, yjyoon-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/player/PlayerUiState.kt
> +    object Empty : PlayerUiState()
![image](https://user-images.githubusercontent.com/72238126/174465710-13c9be0b-000a-47ed-a3a8-b36b6d568677.png)

위 화면들이 Empty 상태 아닌가요?

2022-06-19 04:55 UTC, laco-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/player/PlayerUiState.kt
> +    object Empty : PlayerUiState()
세개가 다 없는 경우 보여주는UI가 다름 -> 운영 클래스

2022-06-19 05:58 UTC, yjyoon-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/player/CopyButton.kt
> +    kakaoId: String,
[79f2ebc](https://github.com/YAPP-Github/20th-ALL-Rounder-Team-2-Android/pull/160/commits/79f2ebcc72b988291454b53d2c7da4ad92816204)

`KakaoIdCopyButton` 으로 전용적 네이밍으로 수정하였습니다.

2022-06-19 05:59 UTC, yjyoon-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/player/PlayerContent.kt
> +        item { KnowllyDivider() }
[29a46eb](https://github.com/YAPP-Github/20th-ALL-Rounder-Team-2-Android/pull/160/commits/29a46eb611c93daf5e59859f00a587f01921a74a)

LazyColumn에서 빼고 상위 컴포넌트에서 선언하였습니다.

2022-06-19 05:59 UTC, yjyoon-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/player/PlayerUiState.kt
> +    object Empty : PlayerUiState()
[99f4236](https://github.com/YAPP-Github/20th-ALL-Rounder-Team-2-Android/pull/160/commits/99f423660a0d294c063d12d59d8ba8867302909d)

Empty 상태 제거했습니다.

2022-06-19 06:00 UTC, yjyoon-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/player/ReviewOutlinedBadge.kt
> +                    modifier = Modifier.padding(start = 2.dp),
[73926da](https://github.com/YAPP-Github/20th-ALL-Rounder-Team-2-Android/pull/160/commits/73926da878342da900d5ce77e2cb9067efd8683c)

신규 애셋으로 업데이트 했습니다.

2022-06-19 07:43 UTC, laco-dev approved these changes

2022-06-19 07:44 UTC, merged