로그인 - 가입 여부 판단
YAPP-Github/20th-ALL-Rounder-Team-2-iOS pull request #173
Opened 2022-06-25 11:17 UTC by yjyoon-dev

## 이슈
- resolved: #171

## 개요
- SignIn 유즈케이스 추가
- IsSignedUp 유즈케이스 추가
- 로그인 과정에서의 화면 이동 분기 구현

2022-06-25 12:14 UTC, laco-dev requested changes

2022-06-25 12:14 UTC, laco-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/login/LoginViewModel.kt
> +        }
isSignedUp이 아닌 경우 early return 하도록 만들어주세요
```kotlin

if (!isSignedUp) {
   _state.value = ...
   return
}
...

```

2022-06-25 12:14 UTC, laco-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/login/LoginViewModel.kt
> +                }
signInUseCase 호출에 실패했을때 예외 처리도 추가해주세요

2022-06-25 12:14 UTC, laco-dev commented on modules/remote/src/main/java/kr/co/knowledgerally/remote/api/ApiService.kt
> +        @Query("provider_name") name: String, @Query("provider_token") accessToken: String
키값이랑 파라미터랑 네이밍 맞춰주세요
두 줄로 바꿔주세요

2022-06-25 12:14 UTC, laco-dev commented on modules/remote/src/main/java/kr/co/knowledgerally/remote/api/ApiService.kt
> +    ): SignUpResponse
SignUpResponse를 `JwtTokenResponseWrapper`로 변경하고 SignInResponse는 지워주세요

2022-06-25 12:14 UTC, laco-dev commented on modules/remote/src/main/java/kr/co/knowledgerally/remote/model/IsSignedUpResponse.kt
> +data class IsSignedUpResponse(
우선은 `UserExistsResponse`가 좋을 것 같습니다.

2022-06-25 12:14 UTC, laco-dev commented on modules/remote/src/main/java/kr/co/knowledgerally/remote/model/IsSignedUpResponse.kt
> +        val isSignedUp: Boolean
요기도 이름 exists로 갑시다

2022-06-26 03:03 UTC, yjyoon-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/login/LoginViewModel.kt
> +        }
[70f04f2](https://github.com/YAPP-Github/20th-ALL-Rounder-Team-2-Android/pull/173/commits/70f04f2ad61fc90dfbe84a669401e5501ec069b4)

수정하였습니다!

2022-06-26 03:04 UTC, yjyoon-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/login/LoginViewModel.kt
> +                }
[70f04f2](https://github.com/YAPP-Github/20th-ALL-Rounder-Team-2-Android/pull/173/commits/70f04f2ad61fc90dfbe84a669401e5501ec069b4)

예외 처리하였습니다.

2022-06-26 03:04 UTC, yjyoon-dev commented on modules/remote/src/main/java/kr/co/knowledgerally/remote/api/ApiService.kt
> +        @Query("provider_name") name: String, @Query("provider_token") accessToken: String
[70f04f2](https://github.com/YAPP-Github/20th-ALL-Rounder-Team-2-Android/pull/173/commits/70f04f2ad61fc90dfbe84a669401e5501ec069b4)

리팩토링 했습니다.

2022-06-26 03:04 UTC, yjyoon-dev commented on modules/remote/src/main/java/kr/co/knowledgerally/remote/model/IsSignedUpResponse.kt
> +data class IsSignedUpResponse(
[70f04f2](https://github.com/YAPP-Github/20th-ALL-Rounder-Team-2-Android/pull/173/commits/70f04f2ad61fc90dfbe84a669401e5501ec069b4)

변경했습니다

2022-06-26 03:04 UTC, yjyoon-dev commented on modules/remote/src/main/java/kr/co/knowledgerally/remote/model/IsSignedUpResponse.kt
> +        val isSignedUp: Boolean
[70f04f2](https://github.com/YAPP-Github/20th-ALL-Rounder-Team-2-Android/pull/173/commits/70f04f2ad61fc90dfbe84a669401e5501ec069b4)

변경했습니다

2022-06-26 03:05 UTC, yjyoon-dev commented on modules/remote/src/main/java/kr/co/knowledgerally/remote/api/ApiService.kt
> +    ): SignUpResponse
[c524a1a](https://github.com/YAPP-Github/20th-ALL-Rounder-Team-2-Android/pull/173/commits/c524a1a316cd274d7c0869b6b57eeb22c5b37237)

다시 확인해보았는데, `/signup` 과 `/signin` 의 response 가 조금씩 달라서 다시 분리했습니다

2022-06-26 03:16 UTC, laco-dev approved these changes

2022-06-26 03:17 UTC, merged