볼 내역 - API
YAPP-Github/20th-ALL-Rounder-Team-2-iOS pull request #177
Opened 2022-06-26 06:07 UTC by yjyoon-dev

## 이슈
- resolved: #109

## 개요
- 기존에 임의로 작성했던 BallRepository, BallCountModel 등 삭제
- GetBallHistoryList 유즈케이스 구현
- UI 에서 유저 정보를 통해 볼 갯수를 가져오도록 수정

2022-06-26 08:07 UTC, laco-dev requested changes

2022-06-26 08:07 UTC, laco-dev commented on modules/remote/src/main/java/kr/co/knowledgerally/remote/model/BallHistoryResponse.kt
> +data class BallHistoryListResponse(
`BallHistoryResponseWrapper`
파일 분리해주세요

2022-06-26 08:07 UTC, laco-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/ball/BallViewModel.kt
> +        .stateIn(viewModelScope, SharingStarted.Eagerly, null)
```kotlin
combine(
   getUserStreamUseCase(),
   getBallHistoryListUseCase()
) { user, ballHistory -> UiState.Success(...) }
```

PresentationModel은 생각이 조금 바뀌어서 당장 필요하지 않으면 Domain 모델 그대로 해도 됩니다

2022-06-26 17:08 UTC, yjyoon-dev commented on modules/remote/src/main/java/kr/co/knowledgerally/remote/model/BallHistoryResponse.kt
> +data class BallHistoryListResponse(
[44f6dce](https://github.com/YAPP-Github/20th-ALL-Rounder-Team-2-Android/pull/177/commits/44f6dce62ec6c3d90ac4b13c0c80e445df050bfe)

분리했습니다

2022-06-26 17:09 UTC, yjyoon-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/ball/BallViewModel.kt
> +        .stateIn(viewModelScope, SharingStarted.Eagerly, null)
[10ae0b2](https://github.com/YAPP-Github/20th-ALL-Rounder-Team-2-Android/pull/177/commits/10ae0b239e1c2c54ee1e3709011f6925e20d4715)

이번 기회에 `combine`을 익혀보고 싶어서 시도해보았는데....
처참한 코드가 나온 것 같습니다...

2022-06-27 10:54 UTC, laco-dev requested changes
PresentationModel 삭제하고, Domain 모델 사용하도록 변경해주세요 🙏🏻

2022-07-01 07:43 UTC, laco-dev approved these changes

2022-07-01 07:44 UTC, merged