운영 및 수강 클래스 조회 기능
YAPP-Github/20th-ALL-Rounder-Team-2-iOS pull request #187
Opened 2022-07-02 22:04 UTC by yjyoon-dev

## 이슈
- resolved: #186

## 개요
- 운영 및 수강 클래스에 대해 `Lesson` 도메인 모델 하나로 통일하여 구현했습니다.
- 구현 과정에서 네이밍 변경을 많이 했는데 혹시 몰라 커밋을 따로 분리했습니다.
- 도메인 리뷰가 완료되면 직접적인 UI 연결 작업까지 진행하겠습니다.

## 이슈
- LocalDateTime 계산 관련 API는 전부 SDK 버전을 최소 26 이상을 요구하는 것 같습니다. (클래스 진행 소요시간 표시할 때 필요)

2022-07-03 04:36 UTC, laco-dev requested changes
`lecture`가 아닌 `lesson`이라고 변경한 이유가 무엇인가요?

2022-07-03 04:37 UTC, laco-dev commented
> LocalDateTime 계산 관련 API는 전부 SDK 버전을 최소 26 이상을 요구하는 것 같습니다. (몇 시간 짜리 클래스인지 표시할 때 필요)

desugaring 추가된 코드 참고해서 build.gradle에 추가해주세요

2022-07-03 07:10 UTC, yjyoon-dev commented
> `lecture`가 아닌 `lesson`이라고 변경한 이유가 무엇인가요?

예전에 안드로이드에서는 `lesson`으로 통일하기로 했던 것 같아서요..! 백엔드와 통합하는 게 낫다고 생각하시면 `lecture`로 변경하겠습니다.

2022-07-03 07:24 UTC, laco-dev commented
이전에는 확정되기전이라,,, 🙏🏻  
통일하시죠. 도메인 개념이라 다르게 가져가지 않아도 될 것 같습니다.

2022-07-03 08:47 UTC, yjyoon-dev commented
- 네이밍 관련해서 `Lecture`로 모두 통일했습니다
- desugaring 코드 추가해서 날짜 포매팅 했습니다.

2022-07-04 14:27 UTC, laco-dev requested changes
UI를 먼저 바꿀 필요가 없었는데,,
같이 섞여서 코드 변경이 많아진 것 같습니다. 🤔

2022-07-04 14:27 UTC, laco-dev commented on modules/data/src/main/java/kr/co/knowledgerally/data/di/RepositoryModule.kt
> +    abstract fun bindLessonRepository(repo: LectureRepositoryImpl): LectureRepository
이름 같이 바꿔주세요

2022-07-04 14:27 UTC, laco-dev commented on modules/domain/src/main/java/kr/co/knowledgerally/domain/model/Lecture.kt
> +    val playerKakaoId: String?,
우리 입장에서 이 두 개의 필드가 필요할까요?

2022-07-04 14:27 UTC, laco-dev commented on modules/domain/src/main/java/kr/co/knowledgerally/domain/model/Lecture.kt
> +    val applicants: List<Applicant>?,
리스트 타입은 도메인 레벨에서 nullable로 만들지 말아주세요.
없는 경우 비어있는 리스트를 사용합니다

2022-07-04 14:27 UTC, laco-dev commented on modules/domain/src/main/java/kr/co/knowledgerally/domain/model/Lecture.kt
> +    }
이 개념에 대해 Type 대신 적절한 이름으로 변경 해주세요.

2022-07-04 14:27 UTC, laco-dev commented on modules/domain/src/main/java/kr/co/knowledgerally/domain/model/Lecture.kt
> +data class Lecture(
Lecture에 모두 풀어서 쓰는 대신, LectureInfo로 구조화 해서 만들어주세요

2022-07-04 14:27 UTC, laco-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/coach/CoachLectureModel.kt
> +}
도메인 모델에서부터 필요한 개념끼리 모아서 sealed interface로 만들어주세요.

```kotlin
sealed interface Lecture {
   Onboard(...)
   Ongoing(...)
   Done(...)
}

```

2022-07-04 14:27 UTC, laco-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/coach/CoachViewModel.kt
> +                                .map { it.toCoachPresentation() as CoachLectureModel.Completed }
이 세 개의 타입을 가지는 객체를 만들고, 뷰모델이 아닌 유즈케이스에서 로직을 작성 해주세요

2022-07-04 14:27 UTC, laco-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/coach/CompletedTabContent.kt
> +                ),
함수로 분리 해주세요

2022-07-04 14:27 UTC, laco-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/coach/MatchingTabContent.kt
> +import androidx.compose.foundation.layout.*
와일드 카드 import 옵션 꺼주세요.

2022-07-04 14:27 UTC, laco-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/coach/ScheduledTabContent.kt
> +import androidx.compose.foundation.layout.*
와일드 카드 import 옵션 꺼주세요.

2022-07-04 14:27 UTC, laco-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/player/PlayerContent.kt
> +import androidx.compose.foundation.layout.*
와일드 카드 import 옵션 꺼주세요.

2022-07-04 14:27 UTC, laco-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/player/PlayerContent.kt
> +import kr.co.knowledgerally.ui.component.*
와일드 카드 import 옵션 꺼주세요.

2022-07-04 14:27 UTC, laco-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/player/PlayerLectureModel.kt
> +sealed interface PlayerLectureModel {
코치와 같은 의견입니다. 도메인 모델부터 필요한 상태만 모아서 정리해주세요

2022-07-04 17:18 UTC, yjyoon-dev commented on modules/domain/src/main/java/kr/co/knowledgerally/domain/model/Lecture.kt
> +    val playerKakaoId: String?,
![image](https://user-images.githubusercontent.com/72238126/177197414-1b349ca6-0c33-4e65-89ab-18193ee658a9.png)

매칭이 성사된 운영클래스를 조회할 때 클래스를 수강하게 될 player의 이름과 ID가 필요하지 않을까요?

2022-07-04 19:25 UTC, yjyoon-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/coach/CoachLectureModel.kt
> +}
그러면 domain 모델이 Lecture 단일에서 `CoachLecture`와 `PlayerLecture`로 나뉘게 되고 각각이 Onboard / Ongoing / Done 상태를 갖게 될 것 같은데 제가 이해한 게 맞을까요? 그리고 이렇게 되면 각 상태마다 필요한 개념이 달라 위에서 리뷰해주신 `LectureInfo`로의 구조화가 제 생각엔 힘들 것 같은데 이에 대한 의견도 궁금합니다.

2022-07-05 21:20 UTC, yjyoon-dev commented
- `Applicant` 네이밍을 백엔드 따라 `Forms`로 할까 고민했지만 `Forms` 네이밍이 너무 애매한 것 같아 보류했습니다.
- `Applicant`에 `state`를 추가할까 고민했지만 사실 프론트에선 `REQUEST` 말고는 의미가 없을 것 같아 보류했습니다.
- `matchedUser`나 `coach`가 `User` 모델을 그대로 사용하면 조금 과하지 않나 싶었지만 이름과 카톡 ID 외의 정보가 필요해질 수도 있고, 이름이랑 카톡 ID만 갖는 모델을 따로 만들기도 애매한 것 같아 그냥 사용했습니다.
- 그러고보니 `Profile`에 카톡 ID가 빠져있어서 remote 모듈까지 수정해놓았습니다.
- 백엔드에서 사용하는 `Onboard / Ongoing` 네이밍이 UI 상에서는 너무 애매하다고 생각하고 TabState도 `Matched / Scheduled`로 사용 중이라 presentation 모듈에서는 직관적인 기존 네이밍을 유지했습니다.

2022-07-05 21:21 UTC, yjyoon-dev commented on modules/data/src/main/java/kr/co/knowledgerally/data/di/RepositoryModule.kt
> +    abstract fun bindLessonRepository(repo: LectureRepositoryImpl): LectureRepository
[e960e9b](https://github.com/YAPP-Github/20th-ALL-Rounder-Team-2-Android/pull/187/commits/e960e9bb898668d247bb18eb45e16bc2442bb90c)

2022-07-05 21:22 UTC, yjyoon-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/player/PlayerLectureModel.kt
> +sealed interface PlayerLectureModel {
[1a15a76](https://github.com/YAPP-Github/20th-ALL-Rounder-Team-2-Android/pull/187/commits/1a15a766eba2a2b50b7393dffcd7b7d3b52e45f3)
[6335df7](https://github.com/YAPP-Github/20th-ALL-Rounder-Team-2-Android/pull/187/commits/6335df760dd5903e9aedfc6393da4f174bf37dd1)

2022-07-05 21:22 UTC, yjyoon-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/coach/CoachViewModel.kt
> +                                .map { it.toCoachPresentation() as CoachLectureModel.Completed }
[1a15a76](https://github.com/YAPP-Github/20th-ALL-Rounder-Team-2-Android/pull/187/commits/1a15a766eba2a2b50b7393dffcd7b7d3b52e45f3)
[6335df7](https://github.com/YAPP-Github/20th-ALL-Rounder-Team-2-Android/pull/187/commits/6335df760dd5903e9aedfc6393da4f174bf37dd1)

2022-07-05 21:22 UTC, yjyoon-dev commented on modules/domain/src/main/java/kr/co/knowledgerally/domain/model/Lecture.kt
> +data class Lecture(
[1a15a76](https://github.com/YAPP-Github/20th-ALL-Rounder-Team-2-Android/pull/187/commits/1a15a766eba2a2b50b7393dffcd7b7d3b52e45f3)
[6335df7](https://github.com/YAPP-Github/20th-ALL-Rounder-Team-2-Android/pull/187/commits/6335df760dd5903e9aedfc6393da4f174bf37dd1)

2022-07-05 21:22 UTC, yjyoon-dev commented on modules/domain/src/main/java/kr/co/knowledgerally/domain/model/Lecture.kt
> +    }
[1a15a76](https://github.com/YAPP-Github/20th-ALL-Rounder-Team-2-Android/pull/187/commits/1a15a766eba2a2b50b7393dffcd7b7d3b52e45f3)
[6335df7](https://github.com/YAPP-Github/20th-ALL-Rounder-Team-2-Android/pull/187/commits/6335df760dd5903e9aedfc6393da4f174bf37dd1)

2022-07-05 21:22 UTC, yjyoon-dev commented on modules/domain/src/main/java/kr/co/knowledgerally/domain/model/Lecture.kt
> +    val applicants: List<Applicant>?,
[1a15a76](https://github.com/YAPP-Github/20th-ALL-Rounder-Team-2-Android/pull/187/commits/1a15a766eba2a2b50b7393dffcd7b7d3b52e45f3)
[6335df7](https://github.com/YAPP-Github/20th-ALL-Rounder-Team-2-Android/pull/187/commits/6335df760dd5903e9aedfc6393da4f174bf37dd1)

2022-07-05 21:22 UTC, yjyoon-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/player/PlayerContent.kt
> +import kr.co.knowledgerally.ui.component.*
[84d11f4](https://github.com/YAPP-Github/20th-ALL-Rounder-Team-2-Android/pull/187/commits/84d11f43770a21881ed8006ef22f994c87cdaa02)

2022-07-05 21:22 UTC, yjyoon-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/player/PlayerContent.kt
> +import androidx.compose.foundation.layout.*
[84d11f4](https://github.com/YAPP-Github/20th-ALL-Rounder-Team-2-Android/pull/187/commits/84d11f43770a21881ed8006ef22f994c87cdaa02)

2022-07-05 21:22 UTC, yjyoon-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/coach/ScheduledTabContent.kt
> +import androidx.compose.foundation.layout.*
[84d11f4](https://github.com/YAPP-Github/20th-ALL-Rounder-Team-2-Android/pull/187/commits/84d11f43770a21881ed8006ef22f994c87cdaa02)

2022-07-05 21:22 UTC, yjyoon-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/coach/MatchingTabContent.kt
> +import androidx.compose.foundation.layout.*
[84d11f4](https://github.com/YAPP-Github/20th-ALL-Rounder-Team-2-Android/pull/187/commits/84d11f43770a21881ed8006ef22f994c87cdaa02)

2022-07-05 21:23 UTC, yjyoon-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/coach/CompletedTabContent.kt
> +                ),
그..어떻게 분리해야 할지 잘 모르겠습니다...

2022-07-05 21:38 UTC, yjyoon-dev commented on modules/domain/src/main/java/kr/co/knowledgerally/domain/model/Lecture.kt
> +    }
[1a15a76](https://github.com/YAPP-Github/20th-ALL-Rounder-Team-2-Android/pull/187/commits/1a15a766eba2a2b50b7393dffcd7b7d3b52e45f3)
[6335df7](https://github.com/YAPP-Github/20th-ALL-Rounder-Team-2-Android/pull/187/commits/6335df760dd5903e9aedfc6393da4f174bf37dd1)

2022-07-05 21:38 UTC, yjyoon-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/player/PlayerContent.kt
> +import androidx.compose.foundation.layout.*
[84d11f4](https://github.com/YAPP-Github/20th-ALL-Rounder-Team-2-Android/pull/187/commits/84d11f43770a21881ed8006ef22f994c87cdaa02)

2022-07-05 21:38 UTC, yjyoon-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/coach/ScheduledTabContent.kt
> +import androidx.compose.foundation.layout.*
[84d11f4](https://github.com/YAPP-Github/20th-ALL-Rounder-Team-2-Android/pull/187/commits/84d11f43770a21881ed8006ef22f994c87cdaa02)

2022-07-06 11:20 UTC, laco-dev requested changes

2022-07-06 11:20 UTC, laco-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/coach/CompletedTabContent.kt
> +                ),
질문을 조금 변경 해볼게요.
가독성을 개선 해주세요 🙏🏻

2022-07-06 11:20 UTC, laco-dev commented on modules/domain/src/main/java/kr/co/knowledgerally/domain/usecase/GetCoachLectureListUseCase.kt
> +) {
반환 타입과 유즈케이스 이름을 맞춰주세요

2022-07-06 11:20 UTC, laco-dev commented on modules/domain/src/main/java/kr/co/knowledgerally/domain/usecase/GetCoachLectureListUseCase.kt
> +    }
`Result.map { ... }` 을 이용 해주세요

2022-07-06 11:20 UTC, laco-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/model/CoachLectureModel.kt
> +}
domain을 바로 사용하지 않고, Model을 추가하신 이유가 무엇인가요.

2022-07-06 12:56 UTC, yjyoon-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/model/CoachLectureModel.kt
> +}
> domain을 바로 사용하지 않고, Model을 추가하신 이유가 무엇인가요.

domain 모델에는 운영클래스와 수강클래스에서 필요한 정보를 모두 담고 있어서, presentation에서 운영 / 수강 클래스 모델을 각각 따로 분리하고 싶었습니다. 예를 들어, `PlayerLectureModel`에는 `applicants`를 담지 않고, `CoachLectureModel`에는 `coach`를 담지 않는 식입니다.

2022-07-06 13:40 UTC, laco-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/model/CoachLectureModel.kt
> +}
> domain 모델에는 운영클래스와 수강클래스에서 필요한 정보를 모두 담고 있어서

그럼 유즈케이스가 분리될 이유가 있을까요?

2022-07-06 13:43 UTC, laco-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/model/CoachLectureModel.kt
> +}
그게 비즈니스로직이라 생각하면, 도메인 모델에 만들면 되는거 아닌가요?

2022-07-06 13:57 UTC, yjyoon-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/model/CoachLectureModel.kt
> +}
비즈니스 로직이라기보단, 오로지 UI 그릴 때 필요한 모델이라고 생각해서 presentation 모듈에 선언했습니다. 또 LectureInfoModel을 속성으로 갖기 때문에 domain에 선언하기 어려울 것 같습니다. LectureInfoModel도 마찬가지로 domain의 LectureInfo에서 UI에 그릴 요소만 포함하는 모델로 재정의하고자 presentation에 생성했습니다.

2022-07-06 13:59 UTC, laco-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/model/CoachLectureModel.kt
> +}
LectureModel은 왜 만들어졌나요?

2022-07-06 14:12 UTC, yjyoon-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/model/CoachLectureModel.kt
> +}
UI에 바로 사용할 수 있도록 runningTime을 갖는 모델로 다시 정의하고 싶어 만들게 되었습니다.

2022-07-06 14:13 UTC, laco-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/model/CoachLectureModel.kt
> +}
```kotlin
data class LectureInfo(...) {
   val runningTime: Long 
}
```
그 의도면 domain에서 만들어도 되는거 아닌가요?

2022-07-06 14:16 UTC, yjyoon-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/model/CoachLectureModel.kt
> +}
음...맞습니다.....

2022-07-06 14:16 UTC, yjyoon-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/model/CoachLectureModel.kt
> +}
너무 UI만을 위해 필요한 정보라 domain에 까지 선언하기 망설였던 것 같습니다

2022-07-06 14:18 UTC, laco-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/model/CoachLectureModel.kt
> +}
`runningTime`을 계산하는 것은 누구의 책임일까요?
```
1. UI (ui)
2. ViewModel (presentation)
3. LectureInfo (domain)
4. Response (remote)
```

질문을 다시, 만약 시작 시간이 오후 3시 종료 시간이 오후 7시일 때, runningTime은 총 4시간이다.
의 테스트 코드를 작성한다면 어디에 작성해야 할까요?

2022-07-06 14:21 UTC, yjyoon-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/model/CoachLectureModel.kt
> +}
너무 자명하게 3번인 것 같습니다..

2022-07-06 14:24 UTC, laco-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/model/CoachLectureModel.kt
> +}
저는 CoachLectureModel, PlayerLectureModel 모두 해당 패키지에 UiState로 존재해도 문제가 없다고 생각합니다.
위에 언급하신 그대로 UI에서 사용하기 위한 객체이지 때문에, model 패키지에 위치하는 것은 맞지 않습니다.

프로젝트 초기에 presentationModel을 애매하게 사용해본 경험이 오히려 발목을 잡는 것 같은데, 아예 없다고 생각 해보세요.

2022-07-06 14:31 UTC, yjyoon-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/model/CoachLectureModel.kt
> +}
아 그래서 초기에 UiState라는 네이밍을 쓰셨던거군요.. 이해가 됐습니다. 조언대로 수정해보겠습니다. 감사합니다!

2022-07-06 21:14 UTC, yjyoon-dev commented on modules/domain/src/main/java/kr/co/knowledgerally/domain/usecase/GetCoachLectureListUseCase.kt
> +) {
[eb0db9e](https://github.com/YAPP-Github/20th-ALL-Rounder-Team-2-Android/pull/187/commits/eb0db9e33ab4fb9fcc4607947bbea55202710820)

2022-07-06 21:14 UTC, yjyoon-dev commented on modules/domain/src/main/java/kr/co/knowledgerally/domain/usecase/GetCoachLectureListUseCase.kt
> +    }
[eb0db9e](https://github.com/YAPP-Github/20th-ALL-Rounder-Team-2-Android/pull/187/commits/eb0db9e33ab4fb9fcc4607947bbea55202710820)

수정했습니다

2022-07-06 21:16 UTC, yjyoon-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/model/CoachLectureModel.kt
> +}
[1ec8dc4](https://github.com/YAPP-Github/20th-ALL-Rounder-Team-2-Android/pull/187/commits/1ec8dc45338502f79954191858942133fecd68a0)

`LectureInfoModel`은 삭제하고 domain 모델로 대체하였고, `Coach/PlayerLectureModel` 은 UiState로 사용하도록 했습니다.

2022-07-07 12:19 UTC, laco-dev approved these changes
고생하셨습니다.

LGTM 🐈 👍🏻 🐕

2022-07-07 14:11 UTC, merged