WebView 및 JS 브릿지
YAPP-Github/20th-ALL-Rounder-Team-2-iOS pull request #190
Opened 2022-07-04 10:30 UTC by yjyoon-dev

## 이슈
- resolved: #168 

## 내용
- WebView 의존성 추가 및 브릿지 적용
- 인터페이스는 기능 구현하며 더 추가할 예정

2022-07-04 10:34 UTC, yjyoon-dev commented
[9924f8e](https://github.com/YAPP-Github/20th-ALL-Rounder-Team-2-Android/pull/190/commits/9924f8e2d1d2cf12809dba3dcf549b87718d3b34)

이상한 커밋이 하나 껴있습니다 죄송합니다..😅

2022-07-04 14:37 UTC, laco-dev requested changes

2022-07-04 14:37 UTC, laco-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/bridge/WebAppInterface.kt
> +    }
AccessToken은 웹 쿠키로 넣도록 논의해서 변경 해주세요

토큰 관련해서도 브릿지로 주고받기 시작하면 너무 빈도수가 높습니다.

2022-07-04 14:37 UTC, laco-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/bridge/WebAppInterface.kt
> +    fun getToken(): String = runBlocking {
https://medium.com/androiddevelopers/create-an-application-coroutinescope-using-hilt-dd444e721528

를 이용하거나, 생성자로 CoroutineScope을 받아주세요

2022-07-04 14:37 UTC, laco-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/home/HomeScreen.kt
> +import androidx.compose.runtime.*
와일드 카드 import 꺼주세요

2022-07-04 14:37 UTC, laco-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/home/HomeScreen.kt
> +                context.getString(R.string.javascript_interface_name)
브릿지 이름은 리소스로 가져오지 않아도 됩니다.

2022-07-04 14:37 UTC, laco-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/main/MainScreen.kt
> +import androidx.compose.material3.*
와일드카드 import 꺼주세요

2022-07-14 13:30 UTC, yjyoon-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/main/MainScreen.kt
> +import androidx.compose.material3.*
[fbc5d5f](https://github.com/YAPP-Github/20th-ALL-Rounder-Team-2-Android/pull/190/commits/fbc5d5ffd67da5cb1722722acc9bb024e26daf6f)

수정했습니다.

2022-07-14 13:30 UTC, yjyoon-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/home/HomeScreen.kt
> +import androidx.compose.runtime.*
[512cdef](https://github.com/YAPP-Github/20th-ALL-Rounder-Team-2-Android/pull/190/commits/512cdefdd21700671b4ea540a0e7c306f4294bd1)

수정했습니다

2022-07-14 13:30 UTC, yjyoon-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/home/HomeScreen.kt
> +                context.getString(R.string.javascript_interface_name)
[c953fbe](https://github.com/YAPP-Github/20th-ALL-Rounder-Team-2-Android/pull/190/commits/c953fbe9a705602d21b6e1afc36263899982026a)

수정했습니다

2022-07-14 13:36 UTC, yjyoon-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/bridge/WebAppInterface.kt
> +    }
해당 PR에 너무 많은 커밋이 엮이는 것 같아서,
혹시 본 PR은 merge 한 후에 쿠키 관련한 내용은
따로 PR 파서 진행해도 될까요?

2022-07-14 13:37 UTC, laco-dev approved these changes

2022-07-14 13:38 UTC, merged