[연습] 이름을 가져오는 기능
YAPP-Github/20th-ALL-Rounder-Team-2-iOS pull request #28
Opened 2022-04-29 08:14 UTC by yjyoon-dev

- resolved : #20

저는 혼날 준비가 되어있습니다...

2022-04-29 13:50 UTC, laco-dev requested changes

2022-04-29 13:50 UTC, laco-dev commented on modules/data/build.gradle.kts
> +}
불필요한 코드 변경입니다.
커밋 하기 전에 한번씩 다시 확인하는 습관을 들여 주세요.

2022-04-29 13:50 UTC, laco-dev commented on modules/domain/src/main/java/com/yapp/domain/repo/UserRepository.kt
> +}
Repository에서 Result 타입을 반환하지 않도록 만든 이유가 무엇인가요?

2022-04-29 13:50 UTC, laco-dev commented on modules/data/src/main/java/com/yapp/data/repo/UserRepositoryImpl.kt
> +    }
엘비스 연산자로 가독성 개선 좋습니다 👍

2022-04-29 13:50 UTC, laco-dev commented on modules/presentation/src/main/java/com/yapp/ui/MainViewModel.kt
> +    }
이름을 가져오는데 실패한 경우 name에 "ERROR" 라는 상태를 보여주도록 만들어 보세요

2022-04-29 13:50 UTC, laco-dev commented on modules/data/src/main/java/com/yapp/data/repo/UserRepositoryImpl.kt
> +    // Remote 에서는 항상 이름을 가져올 수 있다고 가정
항상 이름을 가져온다는 의미가 항상 성공한다는 의미가 아닙니다.

2022-04-29 14:19 UTC, yjyoon-dev commented on modules/domain/src/main/java/com/yapp/domain/repo/UserRepository.kt
> +}
아래에서 지적해주신 것처럼 이름을 가져오는 작업은 항상 성공한다고 가정했어서 그냥 String을 반환하도록 했었습니다 ㅠ 말씀해주신 State 모델링과 더불어 Result를 반환하도록 수정해보겠습니다

2022-04-29 14:21 UTC, yjyoon-dev commented on modules/data/build.gradle.kts
> +}
이런 것에 신경을 못썼네요. 한 번씩 꼭 체크하도록 하겠습니다

2022-04-30 09:16 UTC, yjyoon-dev commented on modules/data/src/main/java/com/yapp/data/repo/UserRepositoryImpl.kt
> +    // Remote 에서는 항상 이름을 가져올 수 있다고 가정
[3106eda](https://github.com/YAPP-Github/20th-ALL-Rounder-Team-2-Android/pull/28/commits/3106edad1ad33ba9dcbe38109b879fdf43185200)

임의의 확률로 실패하도록 구현했습니다

2022-04-30 09:16 UTC, yjyoon-dev commented on modules/presentation/src/main/java/com/yapp/ui/MainViewModel.kt
> +    }
[7ced170](https://github.com/YAPP-Github/20th-ALL-Rounder-Team-2-Android/pull/28/commits/7ced170056727c5f0cf2b44ede4d395cf87951c4)

NameState 를 정의하고 성공 및 실패에 따른 상태를 표현하도록 했습니다

2022-04-30 09:36 UTC, laco-dev requested changes

2022-04-30 09:36 UTC, laco-dev commented on modules/data/src/main/java/com/yapp/data/repo/UserRepositoryImpl.kt
> +        else name
실패했을 경우가 아닌 비어있을 경우 서버에서 가져오도록 요청을 드렸습니다.
로직 다시 확인 해 주세요

2022-04-30 09:36 UTC, laco-dev commented on modules/remote/src/main/java/com/yapp/remote/source/UserRemoteDataSourceImpl.kt
> +        else Result.failure(IllegalArgumentException())
if else의 괄호를 열지 않고 각각 한줄로 작성하는건 컨벤션에 맞지 않습니다.

간단한 경우 if else 합쳐서 한줄로 작성을 하되 여러줄인경우 반드시 괄호를 넣어 주세요

2022-04-30 09:36 UTC, laco-dev commented on modules/presentation/src/main/java/com/yapp/ui/MainActivity.kt
> +    when(nameState) {
코드 리포매팅 해주세요

2022-04-30 11:35 UTC, yjyoon-dev commented on modules/presentation/src/main/java/com/yapp/ui/MainActivity.kt
> +    when(nameState) {
[6952c25](https://github.com/YAPP-Github/20th-ALL-Rounder-Team-2-Android/pull/28/commits/6952c250626afa2c9f09e2cb94d86d8ff493cc87)

리포매팅 완료했습니다

2022-04-30 11:37 UTC, yjyoon-dev commented on modules/data/src/main/java/com/yapp/data/repo/UserRepositoryImpl.kt
> +        else name
[15c3181](https://github.com/YAPP-Github/20th-ALL-Rounder-Team-2-Android/pull/28/commits/15c3181c3b2518591f05e7ef817bacc2c756a863)

요청하신 로직으로 다시 재구현하였습니다

2022-04-30 11:38 UTC, yjyoon-dev commented on modules/remote/src/main/java/com/yapp/remote/source/UserRemoteDataSourceImpl.kt
> +        else Result.failure(IllegalArgumentException())
[a35506f](https://github.com/YAPP-Github/20th-ALL-Rounder-Team-2-Android/pull/28/commits/a35506f21bd98508dbc2842f8004300a25514737)

코드 컨벤션에 맞추어 코드 수정하였습니다. 컨벤션 숙지하도록 하겠습니다!

2022-04-30 12:01 UTC, laco-dev requested changes

2022-04-30 12:01 UTC, laco-dev commented on modules/data/src/main/java/com/yapp/data/repo/UserRepositoryImpl.kt
> +        }
마지막으로 
위 코드를 runCatching을 사용하지 않고 동일한 구현을 하도록 만들어 주세요.

```kotlin
// Hint
Result.exceptionOrNull()
```

2022-04-30 13:02 UTC, yjyoon-dev commented on modules/data/src/main/java/com/yapp/data/repo/UserRepositoryImpl.kt
> +        }
[d0a33b6](https://github.com/YAPP-Github/20th-ALL-Rounder-Team-2-Android/pull/28/commits/d0a33b6d19413605f2c24e9141a3702a408cc808)

힌트주신 `mapCatching()` 은 이용하였는데
`exceptionOrNull()`은 사용처를 찾지 못했습니다 ㅠㅠ

2022-04-30 13:20 UTC, laco-dev commented on modules/data/src/main/java/com/yapp/data/repo/UserRepositoryImpl.kt
> +        }
```kotlin
override suspend fun getName(): Result<String> {
    val result = userLocalDataSource.getName()
    val exception = result.exceptionOrNull()
    if (exception != null) {
        return Result.failure(exception)
    }
    
    val name = result.getOrThrow()
    return if (name.isNullOrEmpty()) {
        userRemoteDataSource.getName()
    } else {
        Result.success(name)
    }
}
```
둘 다 사용할 수 있어서, 편한 방법을 쓰면 됩니다. 😄

2022-04-30 13:21 UTC, laco-dev approved these changes
Result 이정도로 사용 해 보셨으면 왠만한 상황에서는 응용 가능하실겁니다.
고생 많으셨습니다.

LGTM 🐈 👍 🐕

2022-04-30 13:21 UTC, laco-dev commented on modules/data/src/main/java/com/yapp/data/repo/UserRepositoryImpl.kt
> +        return name
굳이 name이라는 변수를 만들어 반환할 필요가 없어 보이는 코드네요 ㅎ

2022-04-30 13:31 UTC, yjyoon-dev commented on modules/data/src/main/java/com/yapp/data/repo/UserRepositoryImpl.kt
> +        }
아하, 감사합니다!!

2022-04-30 13:31 UTC, yjyoon-dev commented on modules/data/src/main/java/com/yapp/data/repo/UserRepositoryImpl.kt
> +        return name
앗 그러네요...ㅎㅎ 항상 꼼꼼한 리뷰 감사합니다!!😀😀

2022-04-30 13:34 UTC, merged