[ISSUE-056] 임시 로그인 화면 구현
YAPP-Github/20th-ALL-Rounder-Team-2-iOS pull request #60
Opened 2022-05-08 15:15 UTC by yjyoon-dev

resolved : #56

2022-05-09 03:27 UTC, laco-dev requested changes

2022-05-09 03:27 UTC, laco-dev commented on modules/presentation/src/main/java/kr/co/yapp/knowlly/ui/login/LoginPlatform.kt
> +    enum class Type { GOOGLE, KAKAO }
구글 카카오만 다른 파일로 분리 해주세요

2022-05-09 03:27 UTC, laco-dev commented on modules/presentation/src/main/java/kr/co/yapp/knowlly/ui/login/LoginScreen.kt
> +}
너무 힘을 쓰시는 것 같은데 삭제될 코드라 Platform 개념 삭제하고 단순하게 Button만 추가 해주세요

2022-05-09 03:27 UTC, laco-dev commented on modules/presentation/src/main/java/kr/co/yapp/knowlly/ui/splash/SplashActivity.kt
> +        }
UI State를 어떻게 처리하는지와 코루틴을 공부 하시고 위 구조가 무엇이 잘못되었는지 알려주세요
https://developer.android.com/jetpack/guide/ui-layer?hl=ko

2022-05-09 03:27 UTC, laco-dev commented on modules/presentation/src/main/java/kr/co/yapp/knowlly/ui/splash/SplashViewModel.kt
> +        this.launch {
this 빼주세요

2022-05-09 16:44 UTC, yjyoon-dev commented on modules/presentation/src/main/java/kr/co/yapp/knowlly/ui/splash/SplashViewModel.kt
> +        this.launch {
[ddb9978](https://github.com/YAPP-Github/20th-ALL-Rounder-Team-2-Android/pull/60/commits/ddb9978736f781bdb3abce20b7f13a218ffd2729)

제거했습니다

2022-05-09 16:44 UTC, yjyoon-dev commented on modules/presentation/src/main/java/kr/co/yapp/knowlly/ui/splash/SplashActivity.kt
> +        }
[ddb9978](https://github.com/YAPP-Github/20th-ALL-Rounder-Team-2-Android/pull/60/commits/ddb9978736f781bdb3abce20b7f13a218ffd2729)

Ui State 관련하여 StateFlow 를 collect 하게끔 수정하였습니다

2022-05-09 16:45 UTC, yjyoon-dev commented on modules/presentation/src/main/java/kr/co/yapp/knowlly/ui/login/LoginScreen.kt
> +}
[eb116e6](https://github.com/YAPP-Github/20th-ALL-Rounder-Team-2-Android/pull/60/commits/eb116e6b79e44085eae106bda836e9d173dad918)

경량화 했습니다

2022-05-09 16:45 UTC, yjyoon-dev commented on modules/presentation/src/main/java/kr/co/yapp/knowlly/ui/login/LoginPlatform.kt
> +    enum class Type { GOOGLE, KAKAO }
[eb116e6](https://github.com/YAPP-Github/20th-ALL-Rounder-Team-2-Android/pull/60/commits/eb116e6b79e44085eae106bda836e9d173dad918)

따로 분리했습니다

2022-05-10 04:24 UTC, laco-dev approved these changes
고생하셨습니다.
개선 필요한 부분은 #61 작업에서 제가 이어서 수정 하면 작성하신 코드랑 비교 해 보도록 하세요.

이 PR은 우선 병합  해주세요

2022-05-10 04:48 UTC, merged