카카오 로그인
YAPP-Github/20th-ALL-Rounder-Team-2-iOS pull request #85
Opened 2022-05-21 08:56 UTC by yjyoon-dev

- resolved: #42

2022-05-21 08:56 UTC, yjyoon-dev commented
- SDK 로그인은 context가 필요하기 때문에 activity에서 호출하는 것이 좋다고 생각했습니다
- onSocialLogin과 onServiceLogin이 나뉘어진 것이 마음에 안드는데 마땅히 어디서 이 둘을 통합해야 좋을지 모르겠습니다..
- LoginSdk.kt 에서 Result를 뭔가 허접하게 사용한 것 같고 SocialUserInfo가 null일 때의 예외처리도 애매한 것 같습니다

2022-05-22 07:24 UTC, laco-dev requested changes
구글 로그인은 카카오랑 방식이 완전 다릅니다.
1. 구글 로그인: Activity에서 바로 실행해서 onActivityResult로 핸들링
2. 카카오: 별도의 액티비티 실행해서 내부적으로 핸들링

타입에 따라 일반화를 하려면 구조부터 추상화를 해야 합니다.
그리고 별도 액티비티에서 모든 것을 캡슐화 해서 처리해야 합니다.

위 설계대로 하기에는 복잡도가 너무 높아서, 권장드리지 않습니다.

```kotlin
fun googleLogin()
fun kakaoLogin()
```

위 개념이 아니라 `interface Auth { ... }` 형태로 만들어집니다.
구글 개념은 제외하고 만들어주세요

2022-05-22 07:24 UTC, laco-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/login/LoginScreen.kt
> +    onSocialLogin: (LoginTypeModel) -> Result<SocialUserInfo?>,
리턴 형태로 받지 않도록 해주세요.
콜백이 필요한 경우 뷰모델에서 상태를 변경하도록 하면 됩니다.

2022-05-22 07:24 UTC, laco-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/login/LoginSdk.kt
> +        }
함수 분리 해 주세요.

2022-05-22 11:57 UTC, yjyoon-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/login/LoginSdk.kt
> +        }
분리 했습니다

[3ec2ae8](https://github.com/YAPP-Github/20th-ALL-Rounder-Team-2-Android/pull/85/commits/3ec2ae8cc27eb0da01484fd6ce47d382b09c700f)

2022-05-22 11:58 UTC, yjyoon-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/login/LoginScreen.kt
> +    onSocialLogin: (LoginTypeModel) -> Result<SocialUserInfo?>,
리팩토링 해보았습니다

[15acfc3](https://github.com/YAPP-Github/20th-ALL-Rounder-Team-2-Android/pull/85/commits/15acfc3db87bd3006c3eff77a8b673a60564a176)

2022-05-22 13:30 UTC, laco-dev requested changes

2022-05-22 13:30 UTC, laco-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/login/KakaoSdk.kt
> +        }
비동기로 동작하는 코드입니다. 
결과가들어오기 전에 아래 코드로 내려갑니다.

2022-05-22 13:30 UTC, laco-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/login/KakaoSdk.kt
> +        return result // FIXME: UI에서 항상 초깃값인 Result.Success(null)을 반환하는 버그
동일하게 위 Kakao 로그인 구조 모두 비동기로 동작합니다.
왜 result가 바로 반환되는지 생각해보세요

2022-05-22 13:30 UTC, laco-dev commented on modules/presentation/src/main/java/kr/co/knowledgerally/ui/login/LoginScreen.kt
> +                    .onFailure { onFailToLogin() }
컴포저블에서는 외부 의존성을 사용하지 말아주세요.
Activity에서 호출하고 결과가 ViewModel로 넘어가서 State가 변경되게 해주세요

2022-05-22 13:46 UTC, merged